#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, re, sys, time, argparse, array
import pandas as pd
import numpy as np
import multiprocessing as mp
from copy import deepcopy
from collections import OrderedDict
from basalkit_functions_filterTC import *

ScriptName=re.split('/', sys.argv[0])[-1]
cmds=OrderedDict([("avgmod","Calculate average modification level(AvgMod) of tested nucleotide(e.g. 5mC/6mA)"),\
                  ("regmod","Summarise nucleotide modification level at given regions"),\
                  ("epiallele","Extract epialleles from aligned reads"),\
                  ("measure","Calculate various measures of nucleotide modification, including AvgMod, CAMDA, CHALM, PDR, Entropy, Epipolymorphism, MHL, and FDRP"),\
                  ("propa","Detecting methylation propagation events at given regions")
                  ])

def printHelp():
    print("BASAL Toolkit\n")
    print("For help information of each function, try:\n")
    print("  python "+ScriptName+" <Function> -h\n")
    print("Availible Functions:\n")
    for i in cmds.keys():
        print('  '+i+'\t'+cmds[i]+'\n')

def main(cmd=''):
    # check whether the requested function is included
    if cmd not in cmds.keys():
        print("Function ",cmd," not found, please see the help below:\n")
        printHelp()
        #sys.exit()
        return False

    # parse parameters
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,\
                                     usage='python '+ScriptName+' '+cmd+' <positional arguments> [optional arguments]\n',\
                                     description=cmds[cmd]+"\n",\
                                     epilog='')
    # designate the first positional argument as ' '
    parser.add_argument(' ',default=None,help='')

    # parse input parameters of each function
    if cmd=="avgmod":
        parser.add_argument('Alignments',default=None,\
                            help="Aligned reads stored in SAM/BAM files. Multiple files generated by the same aligner are seperated by ','.")
        parser.add_argument('Reference',default=None,\
                            help="Reference genome sequence in fasta format.")
        parser.add_argument("-M", "--converted_base",dest="converted_base",default="TC",\
                            help='Base-conversion information in the format of two different nucleotides N1N2, indicating N1 nucleotide in the reads could be mapped to N2 nucleotide in the reference sequences. "-M TC"(the default) can detect C=>U(T) conversion in DNA bisulfite sequencing or EM-seq. "-M GA" can detect A=>I(G) conversion in RNA m6A sequencing (e.g. GLORI) or DNA 6mA sequencing (e.g. NT-seq).')
        parser.add_argument("-D", "--conversion_mode",dest="conversion_mode",default="U",\
                            help='Base-conversion mode, whether the modified(-D M) or unmodified(-D U, the default) N2 nucleotides are converted to N1 nucleotides. For example, "-M TC -D U" can detect 5mC in bisulfite-seq or EM-seq; "-M TC -D M" can detect 5mC in TAPS; "-M GA -D U" can detect m6A in GLORI, as well as 6mA in NT-seq.')
        parser.add_argument("-a", "--aligner",dest="aligner",default="BASAL",\
                            help='Because different aligners store mapping strand information in different ways, currently only the alignments of these aligners are supported: BASAL, Bismark and gemBS. The "BASAL" option is also supportive for BSMAP alignments.')
        parser.add_argument('-e', '--camda',action="store_true",dest="camda",default=False,\
                            help="If set, methylation concurrence ratio (CAMDA) of each tested nucleotide will be generated.")
        parser.add_argument('-o', '--tsv_prefix',dest="tsv_prefix",default='output',\
                            help="Prefix of output tsv files saving AvgMod or CAMDA of each tested nucleotide.")
        parser.add_argument('-w', '--wig_prefix',dest="wig_prefix",default=None,\
                            help="Prefix of output wiggle files saving AvgMod or CAMDA. As default, NO wiggle file is saved.")
        parser.add_argument('-b', '--wig_bin',dest="wig_bin",metavar='BIN',type=int,default=25,\
                            help="Bin size for wiggle files.")
        parser.add_argument('-c', '--chroms',dest="chroms",metavar='CHR',default=None,\
                            help="Only process given chromosomes, which separated by ','. For example, 'chr1,chr2'. As default, all chromosomes are processed.")
        parser.add_argument('-s', '--sam_path',dest="sam_path",metavar='PATH',default=None,\
                            help="Path to samtools.")
        parser.add_argument('-u', '--unique',action="store_true",dest="unique",default=False,\
                            help="Only process unique mappings/pairs.")
        parser.add_argument("-p", "--pair", action="store_true", dest="pair",default=False,\
                            help="Only process properly paired mappings.")
        parser.add_argument("-r", "--rm_dup", action="store_true", dest="rm_dup",default=False,\
                            help="Remove duplicated reads.")
        parser.add_argument("-t", "--trim_fillin", dest="trim_fillin", type=int, metavar='N', default=0,\
                            help="Trim N end-repairing fill-in nucleotides.")
        parser.add_argument("-g", "--combine", action="store_true", dest="combine", default=False,\
                            help="If set, reads from both Waston and Crick strands covering the same CpG are combined. This option is only valid if -M TC.")
        parser.add_argument("-m", "--min_depth", dest="min_depth", type=int, metavar='FOLD', default=4,\
                            help="Report loci with sequencing depth>=FOLD.")
        parser.add_argument("-i", "--handle_SNP", dest="handle_SNP", default="no-action",\
                            help='How to handle CT(for -M TC) or AG(for -M GA) SNP? Must be one of ["no-action","correct","skip"].')
        parser.add_argument("-x", "--context", dest="context", default=None,\
                            help='Select the sequence context of modified bases. For -M TC, available options are "TC","AC","GC","CC". For -M GA, available options are "GAC","AAC","YAC","GAD","AAD","YAD". Multiple options are separated by ",". As default of -M TC, all 4 types(TC,AC,GC,CC) are processed.')
    if cmd=="regmod":
        parser.add_argument('Bed',default=None,\
                            help="Genomic regions in bed file with at least the first 3 columns")
        parser.add_argument('AvgMod',default=None,\
                            help="AvgMod (or CAMDA) file generated by 'avgmod' command")
        parser.add_argument('-s', '--usestrand',action="store_true",dest="usestrand",default=False,\
                            help="Use the strand information(6th column) in Bed file, then reads on forward and reverse strands will not be combined.")
        parser.add_argument('-o', '--output',dest="OUT",metavar='',default='region_ratio.tsv',\
                            help="Output file name")
    if cmd=="epiallele":
        parser.add_argument('Alignments',default=None,\
                            help="Aligned reads stored in SAM/BAM files. Multiple files generated by the same aligner are seperated by ','.")
        parser.add_argument('Reference',default=None,\
                            help="Reference genome sequence in fasta format.")
        parser.add_argument("-M", "--converted_base",dest="converted_base",default="TC",\
                            help='Base-conversion information in the format of two different nucleotides N1N2, indicating N1 nucleotide in the reads could be mapped to N2 nucleotide in the reference sequences. "-M TC"(the default) can detect C=>U(T) conversion in DNA bisulfite sequencing or EM-seq. "-M GA" can detect A=>I(G) conversion in RNA m6A sequencing (e.g. GLORI) or DNA 6mA sequencing (e.g. NT-seq).')
        parser.add_argument("-D", "--conversion_mode",dest="conversion_mode",default="U",\
                            help='Base-conversion mode, whether the modified(-D M) or unmodified(-D U, the default) N2 nucleotides are converted to N1 nucleotides. For example, "-M TC -D U" can detect 5mC in bisulfite-seq or EM-seq; "-M TC -D M" can detect 5mC in TAPS; "-M GA -D U" can detect m6A in GLORI, as well as 6mA in NT-seq.')
        parser.add_argument("-a", "--aligner",dest="aligner",default="BASAL",\
                            help='Because different aligners store mapping strand information in different ways, currently only the alignments of these aligners are supported: BASAL, Bismark and gemBS. The "BASAL" option is also supportive for BSMAP alignments.')
        parser.add_argument('-c', '--chroms',dest="chroms",metavar='CHR',default=None,\
                            help="Only process given chromosomes, which separated by ','. For example, 'chr1,chr2'. As default, all chromosomes are processed.")
        parser.add_argument('-o', '--output',dest="output",metavar='OUTPUT',default='epiallele.tsv',\
                            help="Output epiallele file name.")
        parser.add_argument('-y', '--read_pos',action="store_true",dest="read_pos",default=False,\
                            help="Whether to report the read position on last two columns.")
        parser.add_argument('-s', '--sam_path',dest="sam_path",metavar='PATH',default=None,\
                            help="Path to samtools.")
        parser.add_argument('-u', '--unique',action="store_true",dest="unique",default=False,\
                            help="Only process unique mappings/pairs.")
        parser.add_argument("-p", "--pair", action="store_true", dest="pair",default=False,\
                            help="Only process properly paired mappings.")
        parser.add_argument("-r", "--rm_dup", action="store_true", dest="rm_dup",default=False,\
                            help="Remove duplicated reads.")
        parser.add_argument("-t", "--trim_fillin", dest="trim_fillin", type=int, metavar='N', default=0,\
                            help="Trim N end-repairing fill-in nucleotides.")
        parser.add_argument("-x", "--context", dest="context", default=None,\
                            help='Select the sequence context of modified bases. For -M TC, available options are "TC","AC","GC","CC". For -M GA, available options are "GAC","AAC","YAC","GAD","AAD","YAD". Multiple options are separated by ",". As default of -M TC, all 4 types(TC,AC,GC,CC) are processed.')
    if cmd=="measure":
        parser.add_argument('Bed',default=None,\
                            help="Genomic regions in bed file with at least the first 3 columns")
        parser.add_argument('epiallele',default=None,\
                            help="The compressed(by 'bgzip') and indexed(by 'tabix') epiallele file generated by 'epiallele'")
        parser.add_argument('-n', '--nucleotide',action="store_true",dest="nucleotide",default=False,\
                            help="If set, modification measures of each tested nucleotide(e.g. cytosine) in given regions will be generated; if not(default), for each measure, a summarised score of each region is reported by taking the average of all tested nucleotides.")
        parser.add_argument('-s', '--usestrand',action="store_true",dest="usestrand",default=False,\
                            help="Use the strand information(6th column) in Bed file, then reads on forward and reverse strands will not be combined.")
        parser.add_argument('-w', '--window_size',dest="window_size",type=int,default=4,\
                            help="The number of tested nucleotide(e.g. cytosine) in each window. In the original papers of PDR and Epipolymorphism, this option was designated as 4 (the default). It is only used to calculate the window-based scores, i.e. PDR, Epipolymorphism, Entropy, and MHL.")
        parser.add_argument('-d', '--window_depth',dest="window_depth",type=int,default=4,\
                            help="The minimum reads number covering all tested nucleotides(e.g. cytosine) in the window. It is only used to calculate the window-based scores, i.e. PDR, Epipolymorphism, Entropy, and MHL.")
        parser.add_argument('-m', '--min_depth',dest="min_depth",type=int,default=4,\
                            help="When -n is specified, only nucleotides covered more than this number(-m) of reads are reported.")
        parser.add_argument('-p', '--process_number',dest="process_number",type=int,default=1,\
                            help="The number of processors to use.")
        parser.add_argument('-o', '--output',dest="OUT",metavar='',default='output_measure.tsv',\
                            help="Output file name")
    if cmd=="propa":
        parser.add_argument('Bed',default=None,\
                            help="Genomic regions in bed file with at least the first 3 columns")
        parser.add_argument('epiallele',default=None,\
                            help="The compressed(by 'bgzip') and indexed(by 'tabix') epiallele file generated by 'epiallele'")
        parser.add_argument('-s', '--usestrand',action="store_true",dest="usestrand",default=False,\
                            help="Use the strand information(6th column) in Bed file, then reads on forward and reverse strands will not be combined.")
        parser.add_argument('-o', '--output',dest="OUT",metavar='',default='propa_events.tsv',\
                            help="Output file name")

    # print help information for the requested function
    if '-h' in sys.argv or '--help' in sys.argv:
        parser.print_help()
        return False
    else:
        if len(sys.argv)==2:
            print("Too few arguments. Try:\npython "+ScriptName+" "+cmd+" -h")
            return False

    # save all paramter values in args
    args=parser.parse_args()

    # run function
    if cmd=='avgmod':
        disp("avgmod Started")
        # check options
        if args.converted_base not in ["TC", "GA"]:
            parser.error('Invalid -M value, only "TC" or "GA" is supported')
        if args.conversion_mode not in ["U", "M"]:
            parser.error('Invalid -D value, select "U" or "M"')
        if args.converted_base=="TC":
            if args.aligner not in ["BASAL", "Bismark", "gemBS"]:
                parser.error('Invalid -a value, select "BASAL" or "Bismark" or "gemBS" if -M TC')
        elif args.converted_base=="GA":
            if args.aligner not in ["BASAL"]:
                parser.error('Invalid -a value, select "BASAL" if -M GA')
        if args.sam_path!=None:
            if args.sam_path[-1] != '/': args.sam_path += '/'
        else:
            args.sam_path=""
        if args.chroms!=None:
            args.chroms = set(args.chroms.split(','))
        else:
            args.chroms = set()
        if args.combine==True:
            if args.converted_base!="TC":
                parser.error('-g is only valid for -M TC.')
        handle_SNP_val = {"no-action": 0, "correct": 1, "skip": 2}
        try: args.handle_SNP = handle_SNP_val[args.handle_SNP.lower()]
        except KeyError: parser.error('Invalid -i value, select "no-action", "correct" or "skip"')
        if args.min_depth <= 0: parser.error('Invalid -m value, must >= 1')
        if args.trim_fillin < 0: parser.error('Invalid -t value, must >= 0')
        if args.converted_base=="TC":
            query_base,seq_context_str = "C",['TC','AC','GC','CC']
        elif args.converted_base=="GA":
            query_base,seq_context_str = "A",["GAC","AAC","YAC","GAD","AAD","YAD"]
        if args.context!=None:
            args.context = set(args.context.upper().split(','))
            try: seq_context = set([seq_context_str.index(cc)+1 for cc in args.context])
            except ValueError: parser.error('Invalid -x value. For -M TC, must be one or multiple in ["TC", "AC", "GC", "CC"]. For -M GA, must be one or multiple in ["GAC","AAC","YAC","GAD","AAD","YAD"].')
        else:
            if args.converted_base=="TC":seq_context = set([1, 2, 3, 4])
            elif args.converted_base=="GA":seq_context = set([1,2,3,4,5,6])
        # Load Reference Genome
        ref=Load_Reference(ifile=args.Reference,chroms=args.chroms);
        args.chroms = set(ref.keys())
        # Create arrays
        refmark, coverage, meth0 = {}, {}, {}
        for cr in ref:
            refmark[cr] = array.array('b', [0]) * len(ref[cr])
            meth0[cr] = array.array('H', [0]) * len(ref[cr])
            if args.rm_dup==True:
                coverage[cr] = array.array('B', [0]) * len(ref[cr])
        depth=deepcopy(meth0);
        if args.camda==True:meth1=deepcopy(meth0)
        else:meth1=[]
        if args.handle_SNP > 0:meth_ct=deepcopy(meth0);depth_ct=deepcopy(meth0)
        else:meth_ct=[];depth_ct=[]
        # Mark Reference Genome
        refmark=Mark_Reference(ref=ref,refmark=refmark,converted_base=args.converted_base)
        # Load Alignment
        args.Alignments=set(args.Alignments.split(','))
        meth0,meth1,depth,meth_ct,depth_ct,nmap=Load_Alignment(\
            ifiles=args.Alignments,converted_base=args.converted_base,conversion_mode=args.conversion_mode,aligner=args.aligner,camda=args.camda,ref=ref,refmark=refmark,coverage=coverage,\
            meth0=meth0,meth1=meth1,depth=depth,meth_ct=meth_ct,depth_ct=depth_ct,\
            sam_path=args.sam_path,unique=args.unique,pair=args.pair,rm_dup=args.rm_dup,\
            trim_fillin=args.trim_fillin,chroms=args.chroms,\
            seq_context=seq_context,handle_SNP=args.handle_SNP)
        # Combine cytosine methylation from both strands
        if args.combine==True:
            disp('Combining cytosine methylation from both strands')
            meth0=Combine_Methylation_Both_Strands(ref=ref,uncombined=meth0)
            depth=Combine_Methylation_Both_Strands(ref=ref,uncombined=depth)
            if args.camda==True:
                meth1=Combine_Methylation_Both_Strands(ref=ref,uncombined=meth1)
            if args.handle_SNP > 0:
                meth_ct=Combine_Methylation_Both_Strands(ref=ref,uncombined=meth_ct)
                depth_ct=Combine_Methylation_Both_Strands(ref=ref,uncombined=depth_ct)
        # Output CAMDA,AvgMod files and wiggle file
        Out_base_ratio(tsv_prefix=args.tsv_prefix,wig_prefix=args.wig_prefix,wig_bin=args.wig_bin,camda=args.camda,\
            min_depth=args.min_depth,ref=ref,refmark=refmark,handle_SNP=args.handle_SNP,query_base=query_base,\
            seq_context_str=seq_context_str,seq_context=seq_context,meth0=meth0,meth1=meth1,depth=depth,meth_ct=meth_ct,depth_ct=depth_ct,nmap=nmap)
        # Delete big array to release memory
        del ref, refmark, coverage, depth, meth0, meth1, depth_ct, meth_ct
        disp("avgmod Finished")

    if cmd=='regmod':
        disp("regmod Started")
        Ratio_df=read_methy_files(ifile=args.AvgMod, cols=[0,1,2,6,7])
        o1=open(args.OUT,'w')
        if args.usestrand==True:
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2,5],header=None)
            Bed.columns=["chr","start","end","strand"]
            Bed.sort_values(['chr','strand','start','end'], inplace=True, ascending=True)
            disp("Generating AvgMod ratio for {} Regions ...".format(Bed.shape[0]))
            o1.write('\t'.join(["chr","start","end","strand","AvgMod","site","coverage"])+'\n')
            chr0="";strand0="";
            for row in Bed.iterrows():
                chr1=row[1]['chr'];
                start1=int(row[1]['start']);
                end1=int(row[1]['end']);
                strand1=row[1]['strand']
                if chr1 != chr0 or strand1!=strand0:
                    Ratio_sub=Ratio_df[((Ratio_df['chr']==chr1) & (Ratio_df['strand']==strand1))]
                ratio_list=Region_weighted_Ratio(ratio_sub=Ratio_sub,start=start1,end=end1)
                aline=[chr1,start1,end1,strand1];aline.extend(ratio_list);
                o1.write('\t'.join(map(str,aline))+'\n')
                chr0=chr1;strand0=strand1;
        else:
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2],header=None)
            Bed.columns=["chr","start","end"]
            Bed.sort_values(['chr','start','end'], inplace=True, ascending=True)
            disp("Generating AvgMod ratio for {} regions ...".format(Bed.shape[0]))
            o1.write('\t'.join(["chr","start","end","AvgMod","site","coverage"])+'\n')
            chr0="";
            for row in Bed.iterrows():
                chr1=row[1]['chr'];
                start1=row[1]['start'];
                end1=row[1]['end'];
                if chr1 != chr0:
                    Ratio_sub=Ratio_df[Ratio_df['chr']==chr1]
                ratio_list=Region_weighted_Ratio(ratio_sub=Ratio_sub,start=start1,end=end1)
                aline=[chr1,start1,end1];aline.extend(ratio_list);
                o1.write('\t'.join(map(str,aline))+'\n')
                chr0=chr1;
        o1.close()
        disp("regmod Finished")

    if cmd=='epiallele':
        disp("epiallele Started")
        # check options
        # check options
        if args.converted_base not in ["TC", "GA"]:
            parser.error('Invalid -M value, only "TC" or "GA" is supported')
        if args.conversion_mode not in ["U", "M"]:
            parser.error('Invalid -D value, select "U" or "M"')
        if args.converted_base=="TC":
            if args.aligner not in ["BASAL", "Bismark", "gemBS"]:
                parser.error('Invalid -a value, select "BASAL" or "Bismark" or "gemBS" if -M TC')
        elif args.converted_base=="GA":
            if args.aligner not in ["BASAL"]:
                parser.error('Invalid -a value, select "BASAL" if -M GA')
        if args.sam_path!=None:
            if args.sam_path[-1] != '/': args.sam_path += '/'
        else:
            args.sam_path=""
        if args.chroms!=None:
            args.chroms = set(args.chroms.split(','))
        else:
            args.chroms = set()
        if args.trim_fillin < 0: parser.error('Invalid -t value, must >= 0')
        if args.converted_base=="TC":
            query_base,seq_context_str = "C",['TC', 'AC', 'GC', 'CC']
        elif args.converted_base=="GA":
            query_base,seq_context_str = "A",["GAC","AAC","YAC","GAD","AAD","YAD"]
        if args.context!=None:
            args.context = set(args.context.upper().split(','))
            try: seq_context = set([seq_context_str.index(cc)+1 for cc in args.context])
            except ValueError: parser.error('Invalid -x value. For -M TC, must be one or multiple in ["TC","AC","GC","CC"]. For -M GA, must be one or multiple in ["GAC","AAC","YAC","GAD","AAD","YAD"].')
        else:
            if args.converted_base=="TC":seq_context = set([1, 2, 3, 4])
            elif args.converted_base=="GA":seq_context = set([1,2,3,4,5,6])
        # Load Reference Genome
        ref=Load_Reference(ifile=args.Reference,chroms=args.chroms);
        args.chroms = set(ref.keys())
        # Create arrays
        refmark, coverage = {}, {}
        for cr in ref:
            refmark[cr] = array.array('b', [0]) * len(ref[cr])
            if args.rm_dup==True:
                coverage[cr] = array.array('B', [0]) * len(ref[cr])
        # Mark Reference Genome
        refmark=Mark_Reference(ref=ref,refmark=refmark,converted_base=args.converted_base)
        # Load Alignment
        args.Alignments=set(args.Alignments.split(','))
        # Output epiallele file
        bam2epiallele(ifiles=args.Alignments,converted_base=args.converted_base,conversion_mode=args.conversion_mode,query_base=query_base,aligner=args.aligner,ref=ref,refmark=refmark,coverage=coverage,sam_path=args.sam_path,unique=args.unique,pair=args.pair,rm_dup=args.rm_dup,trim_fillin=args.trim_fillin,seq_context=seq_context,chroms=args.chroms,output=args.output,read_pos=args.read_pos)
        # Delete big array to release memory
        del ref, refmark, coverage
        # sort, compress, tabix
        tmp = os.system("sh {}/epiallele_sort.sh {}".format(sys.path[0],args.output))
        if tmp!=0:
            disp('Failed to sort/compress/tabix epiallele in {}'.format(args.output))
        else:
            disp('Finished sort/compress/tabix epiallele in {}'.format(args.output+".gz"))
        disp("epiallele Finished")

    if cmd=='measure':
        disp("measure Started")
        if os.path.exists(args.epiallele+".tbi")==False:
            tmp = os.system("tabix -b 2 -e 3 {}".format(args.epiallele))
            if tmp!=0:
                disp("Failed to load the tabix index(.tbi) of epiallele file. Exit.")
                sys.exit()
        o1=open(args.OUT,'a+')
        output_col = ["chr","start","end","read_count","AvgMod","CAMDA_weighted","CAMDA_unweighted","CHALM", "PDR", "Entropy", "Epipolymorphism","MHL"]
        # For single nucleotide(-n), the weighted and unweighted CAMDA values are the same.
        if args.nucleotide == True:
            output_col[5]="CAMDA"
            output_col.remove("CAMDA_unweighted")
        if args.usestrand==True:
            output_col.insert(3,"strand")
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2,5],header=None)
            Bed.columns=["chr","start","end","strand"]
        else:
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2],header=None)
            Bed.columns=["chr","start","end"]
        if args.nucleotide == True:
            output_col[1]="pos"
            output_col.remove("end")
        o1.write('\t'.join(output_col)+'\n')
        disp("{} regions loaded from {}".format(Bed.shape[0],args.Bed))

        def writeRegion(output_lines):
            if len(output_lines)>0:
                for line in output_lines:
                    o1.write(line)
        def writeRegion_err(err):
            print(f'error: {str(err)}')

        pool=mp.Pool(args.process_number)
        for region_i in range(Bed.shape[0]):
            pool.apply_async(func=epiallele2score,args=(Bed,region_i,args.epiallele,args.usestrand,args.min_depth,args.window_size,args.window_depth,args.nucleotide),callback=writeRegion,error_callback=writeRegion_err)
        pool.close()
        pool.join()

        o1.close()
        disp("measure Finished")

    if cmd=='propa':
        disp("propa Started")
        if os.path.exists(args.epiallele+".tbi")==False:
            tmp = os.system("tabix -b 2 -e 3 {}".format(args.epiallele))
            if tmp!=0:
                disp("Failed to load the tabix index(.tbi) of epiallele file. Exit.")
                sys.exit()
        epa_col = ['strand','MU_seq','MU_pos','read_count']
        output_col = ["chr","start","end","propagation","M2U","U2M","M2M","U2U"]
        if args.usestrand==True:
            output_col.insert(3,"strand")
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2,5],header=None)
            Bed.columns=["chr","start","end","strand"]
        else:
            Bed=pd.read_csv(args.Bed, sep="\t",usecols=[0,1,2],header=None)
            Bed.columns=["chr","start","end"]
        disp("Detecting propagation events for {} regions ...".format(Bed.shape[0]))
        o1=open(args.OUT,'w')
        o1.write('\t'.join(output_col)+'\n')
        for row in Bed.iterrows():
            chr1=row[1]['chr'];
            start1=int(row[1]['start']);
            end1=int(row[1]['end']);
            output_line=[chr1,start1,end1]
            with os.popen("tabix --verbosity 1 {} {}:{}-{}".format(args.epiallele,chr1,start1,end1)) as file_in:
                epa_df=pd.read_csv(file_in,sep='\t',header=None,usecols=[3,4,5,6],names=epa_col)
                # there is no propagation information if the reads cover only one cytosine
                epa_df=epa_df.loc[epa_df['MU_seq'].str.len()>1]
            if args.usestrand==True:
                strand1=row[1]['strand']
                output_line.extend(strand1)
                epa_df=epa_df[epa_df['strand']==strand1]
            nums=epiallele2ppg(epa_df=epa_df,start=start1,end=end1)
            output_line.extend(nums);
            o1.write('\t'.join(map(str,output_line))+'\n')
        o1.close()
        disp("propa Finished")

if len(sys.argv)>1:
    main(cmd=sys.argv[1])
else:
    printHelp()
